fieldLayouts:
  9299a2a6-8782-4c63-8d11-abc1d246c04c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: coffeeBeans
hasUrls: true
name: 'Coffee Beans'
settings:
  path: '@coffeeBeans'
sortOrder: 0
titleTranslationKeyFormat: null
titleTranslationMethod: null
type: craft\volumes\Local
url: '@coffeeBeans'
