enableVersioning: true
handle: homepage
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  b34dff01-1c91-4de4-ab83-84610f1405d7: # Crafty Commerce
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
